process_noise_covariance:
  - [3.69e-16, 0, 0, 0, 0, 0, 0, 0]
  - [0, 1.58e-16, 0, 0, 0, 0, 0, 0]
  - [0, 0, 8.76e-18, 0, 0, 0, 0, 0]
  - [0, 0, 0, 1.25e-18, 0, 0, 0, 0]
  - [0, 0, 0, 0, 3.51e-18, 0, 0, 0]
  - [0, 0, 0, 0, 0, 3.32e-18, 0, 0]
  - [0, 0, 0, 0, 0, 0, 8.08e-18, 0]
  - [0, 0, 0, 0, 0, 0, 0, 7.22e-14]

measurement_noise_covariance:
  - [4e-18]

initial_error_covariance:
  # 11x11 matrix, rows as lists of values
  - [1.0e-11,    0,    0,    0,    0,    0,    0,    0]
  - [0,    1.0e-11,    0,    0,    0,    0,    0,    0]
  - [0,    0,    1.0e-11,    0,    0,    0,    0,    0]
  - [0,    0,    0,    1.0e-11,    0,    0,    0,    0]
  - [0,    0,    0,    0,    1.0e-11,    0,    0,    0]
  - [0,    0,    0,    0,    0,    1.0e-11,    0,    0]
  - [0,    0,    0,    0,    0,    0,    1.0e-11,    0]
  - [0,    0,    0,    0,    0,    0,    0,    2.0e-11]
