process_noise_covariance:
  # 9x9 matrix, rows as lists of values
  - [0.01, 0,    0,    0,    0,    0,    0,    0,    0]
  - [0,    0.01, 0,    0,    0,    0,    0,    0,    0]
  - [0,    0,    0.01, 0,    0,    0,    0,    0,    0]
  - [0,    0,    0,    0.01, 0,    0,    0,    0,    0]
  - [0,    0,    0,    0,    0.01, 0,    0,    0,    0]
  - [0,    0,    0,    0,    0,    0.01, 0,    0,    0]
  - [0,    0,    0,    0,    0,    0,    0.01, 0,    0]
  - [0,    0,    0,    0,    0,    0,    0,    0.01, 0]
  - [0,    0,    0,    0,    0,    0,    0,    0,    0.01]

measurement_noise_covariance:
  # 1x1 matrix (scalar in list form)
  - [0.1]

initial_error_covariance:
  - [1,    0,    0,    0,    0,    0,    0,    0,    0]
  - [0,    1,    0,    0,    0,    0,    0,    0,    0]
  - [0,    0,    1,    0,    0,    0,    0,    0,    0]
  - [0,    0,    0,    1,    0,    0,    0,    0,    0]
  - [0,    0,    0,    0,    1,    0,    0,    0,    0]
  - [0,    0,    0,    0,    0,    1,    0,    0,    0]
  - [0,    0,    0,    0,    0,    0,    1,    0,    0]
  - [0,    0,    0,    0,    0,    0,    0,    1,    0]
  - [0,    0,    0,    0,    0,    0,    0,    0,    1]