process_noise_covariance:
  # 8x8 matrix, rows as lists of values
  - [1.0e-6, 0,    0,    0,    0,    0,    0,    0    ]
  - [0,    1.0e-6, 0,    0,    0,    0,    0,    0    ]
  - [0,    0,    1.0e-6, 0,    0,    0,    0,    0    ]
  - [0,    0,    0,    1.0e-6, 0,    0,    0,    0    ]
  - [0,    0,    0,    0,    1.0e-6, 0,    0,    0    ]
  - [0,    0,    0,    0,    0,    1.0e-6, 0,    0    ]
  - [0,    0,    0,    0,    0,    0,    1.0e-6, 0    ]
  - [0,    0,    0,    0,    0,    0,    0,    1.0e-6]

measurement_noise_covariance:
  # 1x1 matrix (scalar in list form)
  - [1.0e-16]

initial_error_covariance:
  # 8x8 matrix, rows as lists of values
  - [1.0e-8,    0,    0,    0,    0,    0,    0,    0]
  - [0,    1.0e-8,    0,    0,    0,    0,    0,    0]
  - [0,    0,    1.0e-8,    0,    0,    0,    0,    0]
  - [0,    0,    0,    1.0e-8,    0,    0,    0,    0]
  - [0,    0,    0,    0,    1.0e-8,    0,    0,    0]
  - [0,    0,    0,    0,    0,    1.0e-8,    0,    0]
  - [0,    0,    0,    0,    0,    0,    1.0e-8,   0]
  - [0,    0,    0,    0,    0,    0,    0,    2.0e-8]
