# Other physical parameters

l: 0.24
I0_185: 2.07e-6
I0_254: 5.19e-4
c_h2o: 55.6
epsilon_h2o_185: 0.0324
phi_h2o_185: 0.045
epsilon_h2o_254: 0.032
phi_h2o_254: 0
epsilon_oh_m_185: 3200.0
phi_oh_m_185: 0.11
epsilon_cl_185: 3540.0
phi_cl_185: 0.43
epsilon_so3_185: 3729.5
phi_so3_185: 0.85
epsilon_so3_254: 21.22
phi_so3_254: 0.11
epsilon_pfas_185: 2689.5
epsilon_pfas_254: 28.8
c_cl: 3.0 # M solution
c_so3: 1.0 # M solution